### ISSUE TITLE
Create shedding risk reports

### ISSUE THREAD

**Issue by noamross** [ecohealthalliance/eidith#1]
Based on @rostal's request from the surveillance call, one analysis we will want out of this package is a report on relative viral presence/shedding rates broken up by species, country, region, etc.

This will likely be the first analysis we want out of this package and should be high-priority.

Further info should come on next surveillance call (10/20).

**Comment by arw36** [comment]
Somewhere we will need to incorporate higher taxonomy, so that in addition to species can do analysis and higher taxonomic levels

**Comment by calebasaraba** [comment]
regular surveillance reports have been assigned to `autoeidith` repo
