### ISSUE TITLE
Errors: Downloading P1 and P2 tables 

### ISSUE THREAD

**Issue by soride** [ecohealthalliance/eidith#105]
I just installed the latest version of R and R-Studio and ran into the following errors:

``
> ed_db_check_status() 
Local EIDITH database fields are empty or corrupt. Delete and re-download:
ed_db_delete() followed by ed_db_download().
> eidith::ed_db_delete()
Local EIDITH database successfully deleted.
> ed_db_download()
Using env vars EIDITH_USERNAME and EIDITH_PASSWORD for logon
Downloading and processing EIDITH data. This may take some time.
Downloading PREDICT-1 Event table...

  |==================================================================================| 100%
Importing...

Downloading PREDICT-1 Animal table...

  |==================================================================================| 100%
Importing...

Downloading PREDICT-1 Specimen table...

  |==================================================================================| 100%
Importing...

Downloading PREDICT-1 Test table...

  |==================================================================================| 100%
Importing...

Downloading PREDICT-1 Virus table...

  |==================================================================================| 100%
Importing...

Downloading PREDICT-1 TestIDSpecimenID table...

  |==================================================================================| 100%
Importing...

Error: The fields in the TestIDSpecimenID download are not as expected.  See message for details and ?ed_contact for support.

Error: `df` must be a local dataframe or a remote tbl_sql
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] eidith_0.4.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        dbplyr_1.4.2      pillar_1.4.2      compiler_3.6.1   
 [5] prettyunits_1.0.2 remotes_2.1.0     tools_3.6.1       zeallot_0.1.0    
 [9] testthat_2.3.1    digest_0.6.23     pkgbuild_1.0.6    pkgload_1.0.2    
[13] bit_1.1-14        lifecycle_0.1.0   lubridate_1.7.4   jsonlite_1.6     
[17] tibble_2.1.3      memoise_1.1.0     RSQLite_2.1.4     pkgconfig_2.0.3  
[21] rlang_0.4.2       cli_1.1.0         DBI_1.0.0         rstudioapi_0.10  
[25] curl_4.3          stringr_1.4.0     janitor_1.2.0     httr_1.4.1       
[29] dplyr_0.8.3       withr_2.1.2       hms_0.5.2         rappdirs_0.3.1   
[33] desc_1.2.0        fs_1.3.1          htmlwidgets_1.5.1 vctrs_0.2.0      
[37] devtools_2.2.1    tidyselect_0.2.5  rprojroot_1.3-2   bit64_0.9-7      
[41] DT_0.10           glue_1.3.1        R6_2.4.1          processx_3.4.1   
[45] sessioninfo_1.1.1 tidyr_1.0.0       readr_1.3.1       purrr_0.3.3      
[49] callr_3.3.2       blob_1.2.0        magrittr_1.5      backports_1.1.5  
[53] ps_1.3.0          ellipsis_0.3.0    htmltools_0.4.0   usethis_1.5.1    
[57] assertthat_0.2.1  stringi_1.4.3     crayon_1.3.4     
> ed_db_download(p2_tables)
Using env vars EIDITH_USERNAME and EIDITH_PASSWORD for logon
Downloading and processing EIDITH data. This may take some time.
Error in lapply(p1_tables, function(x) { : object 'p2_tables' not found
> ed_db_download(p2_tables=TRUE)
Using env vars EIDITH_USERNAME and EIDITH_PASSWORD for logon
Downloading and processing EIDITH data. This may take some time.
Downloading PREDICT-1 Event table...

  |==================================================================================| 100%
Importing...

Downloading PREDICT-1 Animal table...

  |==================================================================================| 100%
Importing...

Downloading PREDICT-1 Specimen table...

  |==================================================================================| 100%
Importing...

Downloading PREDICT-1 Test table...

  |==================================================================================| 100%
Importing...

Downloading PREDICT-1 Virus table...

  |==================================================================================| 100%
Importing...

Downloading PREDICT-1 TestIDSpecimenID table...

  |==================================================================================| 100%
Importing...

Downloading PREDICT-2 TRUE table...

  |==================================================================================| 100%
Importing...
Error: no such column: event_name
``

**Comment by emmamendelsohn** [comment]
This has happened to me a few times--it seems to be a hiccup in the server related to the Predict 1 `TestIDSpecimenID` table. I'll look into it, but so far, just rerunning the download has worked for me (and everything just ran fine for me this morning). Let me know if you get the same error again.

**Comment by soride** [comment]
Yes - reran a few times and it eventually worked thanks!
