### ISSUE TITLE
Fake/example data

### ISSUE THREAD

**Issue by noamross** [ecohealthalliance/eidith#22]
Work with METABIOITA/UC Davis teams to create an example fake data set.  @tmorourk can place this at a separate, unsecured API endpoint, and we can include it cached in the package to use for examples and teaching.

**Comment by noamross** [comment]
When this is assembled, it would make sense to use it to write a vignette about the database structure.

**Comment by tmorourk** [comment]
yes it would.  I can get Dan on that.
