### ISSUE TITLE
Better error messages when login credentials fail

### ISSUE THREAD

**Issue by arw36** [ecohealthalliance/eidith#24]
Currently receives "Error: Unknown variables: gains3_event_id, organization_idowner, date_last_updated, crdate, lmdate"

**Comment by noamross** [comment]
It looks like what's happening here is when logging with an account with inadequate access levels, one gets a response, not a 401 error, but the response is an empty table.  So we need to check the server response for completeness, not just HTTP status.

**Comment by noamross** [comment]
@arw36 If you re-install the package, you won't have access yet, but it will tell you so nicely when you try to download things.

**Comment by arw36** [comment]
Not sure if issue with url or my r, but when trying to reinstall get: 

```if (!require(devtools)) install.packages("devtools")
devtools::install_github("ecohealthalliance/eidith")```

Error in curl::curl_fetch_memory(url, handle = handle) : 
  URL using bad/illegal format or missing URL

**Comment by noamross** [comment]
Try again? I just pushed a change that fixed a typo in a dependency name.  Odd that you were able to install it before, though.

**Comment by arw36** [comment]
Works! With a beautiful: ```  Forbidden (HTTP 403). Your account does not have access permissions. Contact technology@eidith.org ```
