### ISSUE TITLE
Re-name or otherwise make clear taxagroup meaning

### ISSUE THREAD

**Issue by calebasaraba** [ecohealthalliance/eidith#32]
Current taxagroup field reflects on-the-ground assignments based on PREDICT categories, not always consistent with scientific taxa (e.g. Brazil marsupials).

**Comment by calebasaraba** [comment]
12/15 Meeting
- Current taxagroup field reflects on-the-ground assignments based on PREDICT categories, not always consistent with scientific taxa (e.g. Brazil marsupials).

**Comment by noamross** [comment]
@rostal  Here are the orders represented in each taxa group in the EIDITH database. Do you want to suggest any re-wording of the `taxagroup names` so it's clear what they are?  We'll make a note in the package metadata tables.

|`taxagroup`          |orders                                                                                                                                                                                                                                                                                                                                                    |
|:------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|Bats               |Chiroptera                                                                                                                                                                                                                                                                                                                                                |
|Birds              |Passeriformes, Strigiformes, Galliformes, Coraciiformes, Gruiformes, Pelecaniformes, Ciconiiformes, Anseriformes, Columbiformes, Psittaciformes, NA, Bucerotiformes, Charadriiformes, Coliiformes, Falconiformes, Podicipediformes, Musophagiformes, Caprimulgiformes, Accipitriformes, Piciformes, Suliformes, Tinamiformes, Eurypygiformes, Apodiformes |
|Carnivores         |Carnivora, NA                                                                                                                                                                                                                                                                                                                                             |
|Non-human Primates |Primates, NA                                                                                                                                                                                                                                                                                                                                              |
|Other Mammals      |Pholidota, Hyracoidea, Macroscelidea, Tubulidentata, Didelphimorphia, Sirenia, Afrosoricida, Cingulata, Pilosa, Lagomorpha, Dermoptera, Proboscidea, NA, Artiodactyla, Erinaceomorpha, Cetacea                                                                                                                                                            |
|Reptiles           |Testudines, Squamata, Crocodilia, NA                                                                                                                                                                                                                                                                                                                      |
|Rodents & Shrews   |Soricomorpha, Rodentia, Scandentia, Didelphimorphia, Macroscelidea, Afrosoricida                                                                                                                                                                                                                                                                          |
|Ungulates          |Artiodactyla, Perissodactyla                                                                                                                                                                                                                                                                                                                              |
|Unknown            |NA, Carnivora

**Comment by noamross** [comment]
Here's the updated taxagroup arrangement that I'm implementing in our processing, based on @rostal's [**suggestions**](https://github.com/ecohealthalliance/eidith/files/669874/recommended.orders.docx).

|taxagroup                  |orders                                                                                                                                                                                                                                                                                                                                                |     n|
|:--------------------------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----:|
|Bats                       |Chiroptera                                                                                                                                                                                                                                                                                                                                            | 24825|
|Birds                      |Accipitriformes, Anseriformes, Apodiformes, Bucerotiformes, Caprimulgiformes, Charadriiformes, Ciconiiformes, Coliiformes, Columbiformes, Coraciiformes, Eurypygiformes, Falconiformes, Galliformes, Gruiformes, Musophagiformes, Passeriformes, Pelecaniformes, Piciformes, Podicipediformes, Psittaciformes, Strigiformes, Suliformes, Tinamiformes |  1851|
|Carnivores                 |Carnivora                                                                                                                                                                                                                                                                                                                                             |  1150|
|Non-Human Primates         |Primates                                                                                                                                                                                                                                                                                                                                              |  8879|
|Other Mammals              |Afrosoricida, Cetacea, Cingulata, Dermoptera, Erinaceomorpha, Hyracoidea, Lagomorpha, Macroscelidea, Pholidota, Pilosa, Proboscidea, Sirenia, Tubulidentata                                                                                                                                                                                           |  1081|
|Reptiles                   |Crocodilia, Squamata, Testudines                                                                                                                                                                                                                                                                                                                      |   504|
|Rodents, Shrews & Opossums |Didelphimorphia, Rodentia, Scandentia, Soricomorpha                                                                                                                                                                                                                                                                                                   | 13620|
|Ungulates                  |Artiodactyla, Perissodactyla                                                                                                                                                                                                                                                                                                                          |  5061|
|NA                         |NA                                                                                                                                                                                                                                                                                                                                                    |    83|
