### ISSUE TITLE
FASTA export feature requests from the viral interpretation team

### ISSUE THREAD

**Issue by noamross** [ecohealthalliance/eidith#39]
-  Break up reports by virus and method
-  use `test_protocol` for method, not `methodology_reference`
-  Export an Excel file to return to the EIDITH team
-  Potentially add a second, space-separated field in the FASTA file which can go into geneious's "Description" field view. 
-  Switch to `sequence_id` from `virus_id`

**Comment by calebasaraba** [comment]
If possible, more detail on the Excel file would be helpful ~ not sure how to implement (is it different than just a ed_tests_report() call nested within a write_csv?)

**Comment by noamross** [comment]
Just forwarded an example.
