### ISSUE TITLE
Make clean version of identified virus_name, like virus_species

### ISSUE THREAD

**Issue by arw36** [ecohealthalliance/eidith#47]
Currently the virus_name in the Test datasheet sometimes includes a phrase. Would be helpful a virus_species variable that lists "Tailam virus"  instead of "strain of Tailam virus". Also clarification on differences between virus_name in the Test data sheet versus Virus datasheet.

**Comment by arw36** [comment]
Also why are there separate virus_name and virus_code variables in Virus datasheet?

**Comment by noamross** [comment]
To do on this:
- [ ] Make the `viral_name` field as part of data processing
- [ ] Document all these fields better in `?ed_metadata`, noting the `virus_code` is just an annotated version of `virus_name`

**Comment by nistara** [comment]
@noamross , in `ed_metadat()` the `order` of the names aren't sequential. If you're working on `ed_metadata` and if there wasn't a reason for the current ordering, that might be something to change.

e.g. 
```
1 events    Event     1 GAINS3_EventID     gains3_event_id         event_id
2 events    Event     5       SiteName           site_name             <NA>
3 events    Event     7      EventName          event_name             <NA>
4 events    Event     8         Region              region             <NA>
5 events    Event     2        Country             country             <NA>
6 events    Event     9      StateProv          state_prov             <NA>
```

**Comment by noamross** [comment]
Thanks, @nistara. You would suggest arranging by `table`, then `order`?

**Comment by nistara** [comment]
@noamross , I would, unless there's a reason we have the current order. It made me wonder if there's something I needed to figure out.

**Comment by arw36** [comment]
Clarifying this virus_name for a virus_species column may need further clarification than simply stripping the "strain of". For instance virus name `Influenza H18N11`, for virus_species should be `Influenza A`, as determined by the interpretation column. But maybe this level of detail should be handled at the project level, and not through the eidith package?

**Comment by noamross** [comment]
Yeah, @arw, I'm beginning to think this should not be in the package at all, but should go into the viral metadata document that we're adding to documentation, along with example code of how to make this manipulation.

**Comment by arw36** [comment]
Yes agree  - considering virus_species depends on varying authorities, for instance many of the known viruses we found have yet to be recognized via ICTV, but are known and in Genbank. So separate projects can determine threshold for considering a separate virus species
