### ISSUE TITLE
Understanding how tables are linked

### ISSUE THREAD

**Issue by nistara** [ecohealthalliance/eidith#49]
To figure out how the tables are connected (what are the common columns, or unique identifier columns across various tables). If there isn't already a schema, I wrote a function utilizing the data from `ed_metadata()`, named `ed_tables_conn()`. This might be useful for users wanting to join tables for further analyses (and for me to modify my previous code for importing into the current `eidith` package). 

```
ed_tables_conn()
```
outputs common `id` columns
```
        T1               T2        conn
1    Event           Animal    event_id
2   Animal         Specimen   animal_id
3 Specimen TestIDSpecimenID specimen_id
4     Test            Virus     test_id
5     Test TestIDSpecimenID     test_id
6    Virus TestIDSpecimenID     test_id
```
A schema derived from the above could be: 
[tbl_conn.pdf](https://github.com/ecohealthalliance/eidith/files/790399/tbl_conn.pdf)

whereas `ed_tables_conn("all")` returns:
```
         T1               T2                conn
1     Event           Animal       database_date
2     Event           Animal        date_created
3     Event           Animal       date_modified
4     Event           Animal            event_id
5     Event         Specimen       database_date
6     Event         Specimen        date_created
7     Event         Specimen       date_modified
8     Event             Test       database_date
9     Event             Test        date_created
10    Event             Test       date_modified
11    Event            Virus       database_date
12    Event            Virus        date_created
13    Event            Virus       date_modified
14   Animal         Specimen           animal_id
15   Animal         Specimen       database_date
16   Animal         Specimen        date_created
17   Animal         Specimen       date_modified
18   Animal             Test       database_date
19   Animal             Test        date_created
20   Animal             Test       date_modified
21   Animal            Virus       database_date
22   Animal            Virus        date_created
23   Animal            Virus       date_modified
24 Specimen             Test       database_date
25 Specimen             Test        date_created
26 Specimen             Test       date_modified
27 Specimen             Test       specimen_type
28 Specimen             Test specimen_type_group
29 Specimen            Virus       database_date
30 Specimen            Virus        date_created
31 Specimen            Virus       date_modified
32 Specimen TestIDSpecimenID         specimen_id
33     Test            Virus       database_date
34     Test            Virus        date_created
35     Test            Virus       date_modified
36     Test            Virus      interpretation
37     Test            Virus            sequence
38     Test            Virus             test_id
39     Test            Virus          virus_name
40     Test TestIDSpecimenID             test_id
41    Virus TestIDSpecimenID             test_id
```
I'll create a pull request if you think the above's useful. If there's already something in place, please let me know!

**Comment by calebasaraba** [comment]
Hi Nistara ~ 
I'm working on a vignette about this, you can see it in progress here:

https://github.com/ecohealthalliance/eidith/blob/examples/inst/data_structure.Rmd

**Comment by noamross** [comment]
Thanks, @nistara. Nice function and figure! Your output actually points out some fields that are redundant across tables, (e.g., `virus_name`). I think we should double-check these to make sure they contain the same information and, if so drop them from post-processed tables, or otherwise rename them (e.g., `interpretation_test`. This way when you merge you won't get `variable.x` and `variable.y` containing the same information.  However, everything also has these 3 date fields.  Should we rename them to reflect tables, e.g., `database_date_event`? Or, just document them more clearly?

**Comment by nistara** [comment]
Thanks @noam! You're right about the merge issues, and it would have been great if they contained the same data, but a small glance reveals that they might not. I think your idea of renaming these fields to reflect the tables is a good one. 

We could also write a wrapper around the `join` functions, which renames fields from respective tables when joining, so that field names aren't changed unless tables are joined. This could be in addition to the better documentation you mentioned as another option.

```
> ea <- inner_join(e, a, by = "event_id")
> table(as.character(ea$date_created.x) == as.character(ea$date_created.y))

FALSE  TRUE 
2547  1998 

> diff = head(which(as.character(ea$date_created.x) != as.character(ea$date_created.y)))
> ea[ diff, c("date_created.x", "date_created.y")]
# A tibble: 6 × 2
       date_created.x      date_created.y
               <dttm>              <dttm>
1 2010-12-23 13:44:45 2011-05-16 17:10:38
2 2010-12-23 13:44:45 2011-05-16 17:10:38
3 2010-12-23 13:44:45 2011-05-16 17:10:38
4 2010-12-23 13:44:45 2011-05-16 17:10:38
5 2010-12-23 13:44:45 2011-05-16 17:10:38
6 2010-12-23 13:44:45 2011-05-16 17:10:38

```

**Comment by noamross** [comment]
We definitely wouldn't expect the date fields to be identical across tables.  I'd be wary about creating a wrapper around `join`, though, because people join in all sorts of ways (using base v. dplyr functions, manual lookups, etc.). So, adding at least one task:

 - [ ] Add table suffixes to `date` fields that have the same name in multiple tables.

**Comment by nistara** [comment]
Sounds good!
