### ISSUE TITLE
Installing 'eidith' package on Jupyter

### ISSUE THREAD

**Issue by PanditPranav** [ecohealthalliance/eidith#51]
Here are some error which I get when I try to install the package on Jupyter. 

**if I install it using**

install.packages("eidith", repos=c("https://ecohealthalliance.github.io/eidith/", getOption("repos")), type="both")

Error in contrib.url(repos, "source"): trying to use CRAN without setting a mirror
Traceback:

1. install.packages("eidith", repos = c("https://ecohealthalliance.github.io/eidith/", 
 .     getOption("repos")), type = "both")
2. contrib.url(repos, "source")
3. stop("trying to use CRAN without setting a mirror")

**It gets installed if I install it following way, but there is an error message** 

install.packages("eidith", repos=c("https://ecohealthalliance.github.io/eidith/"))

Warning message:
"unable to access index for repository https://ecohealthalliance.github.io/eidith/bin/windows/contrib/3.3:
  cannot open URL 'https://ecohealthalliance.github.io/eidith/bin/windows/contrib/3.3/PACKAGES'"installing the source package 'eidith

**Comment by noamross** [comment]
The warning makes sense.  Without `type="both", you're looking for a pre-built binary package, which I don't provide. `"both"` tells your machine to look for a source code version if the pre-built is not available.   This should work without an error:

    install.packages("eidith", repos=c("https://ecohealthalliance.github.io/eidith/"), type="both")

It seems that in the first version you aren't specifying a CRAN repo to get the **eidith** dependencies.   Tell me, in the Jupyter environment, what do you see when you run just `getOption("repos")`?

**Comment by PanditPranav** [comment]
Same error when I do 

install.packages("eidith", repos=c("https://ecohealthalliance.github.io/eidith/"), type="both") 

Generally, I have to specify CRAN repository everytime I install a package on Jupyter environment 

for getOptions('repos') I get 
CRAN
"@CRAN@"
CRANextra
"http://www.stats.ox.ac.uk/pub/RWin"

**Comment by noamross** [comment]
If you need to specify the package every time, that means that there isn't a repo set in `options` so you should install specifically.

    install.packages("eidith", repos=c("https://ecohealthalliance.github.io/eidith/", "https://cran.rstudio.com/"), type="both")

`"both"` I guess is looking for the windows build in my repo, which doesn't exist because I build on the windows machine, but it succeeds anyway because it falls back to the source.  I could recommend type="source", but then all the dependencies would be installed using source, too, which won't work for everyone if they don't have compilers.  

So I think I'll change the recommended install to this, but I could give a warning that an error may appear.  On 0.3.0 I can also see if I can build a windows version to eliminate the error.

**Comment by noamross** [comment]
I've updated this in the tutorial in both the dev branch and the master (currently online).  Adding this TODO for 0.3.0:

- [ ] Add Windows-built package for master releases

**Comment by nistara** [comment]
@noamross , it still gives the following error, and I'm on a mac:
```
Warning message: “unable to access index for repository https://ecohealthalliance.github.io/eidith/bin/macosx/mavericks/contrib/3.3:
  cannot download all files”installing the source package ‘eidith’
```

But `install_github("ecohealthalliance/eidith")` works. Could it have to do with the jupyter notebook itself?

@PanditPranav , when I tried to use R on jupyter notebook, I installed it via `conda install -c r r-essentials`, and then had issues installing packages even in emacs/terminal (had to specify a repository for installing packages, was getting the same error, etc), while RStudio worked just fine. Coincidentally, the R versions were different across RStudio and the other editors, and after much hair pulling I found that anaconda's R, for lack of a better phrase, overrode my original R executable path (`usr/bin/R`) for the emacs/terminal environment. I got rid of anaconda's R essentials, and started running R in Jupyter with the R kernel as outlined [here](https://www.datacamp.com/community/blog/jupyter-notebook-r). All my editors are now accessing the same R kernel, and I don't need to specify a cran repository every time I install a package in jupyter. `getOption("repos")` gives me `CRAN: 'https://cran.r-project.org'`. I presume you're using conda's R essentials, and this might be what's causing you some grief.

**Comment by noamross** [comment]
@nistara That's with `type="both"`?

**Comment by nistara** [comment]
@noamross , yup. And actually, I'm getting the warning across all editors! And there's a small typo in the tutorial.
` install.packages("eidith", repos=c("https://ecohealthalliance.github.io/eidith/", "https://cran.rstudio.com")), type="both")`

**Comment by noamross** [comment]
So it works, but with the _warning_ that you cannot download all files?

**Comment by nistara** [comment]
Yup. Here's the entire message, while installing from RStudio:
```
> install.packages("eidith", repos=c("https://ecohealthalliance.github.io/eidith/", "https://cran.rstudio.com"), type="both")

Warning in install.packages :
  URL 'https://ecohealthalliance.github.io/eidith/bin/macosx/mavericks/contrib/3.3/PACKAGES.gz': status was '404 Not Found'

Warning in install.packages :
  URL 'https://ecohealthalliance.github.io/eidith/bin/macosx/mavericks/contrib/3.3/PACKAGES': status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository https://ecohealthalliance.github.io/eidith/bin/macosx/mavericks/contrib/3.3:
  cannot download all files
installing the source package ‘eidith’

trying URL 'https://ecohealthalliance.github.io/eidith/src/contrib/eidith_0.2.2.tar.gz'
Content type 'application/octet-stream' length 287262 bytes (280 KB)
==================================================
downloaded 280 KB

* installing *source* package ‘eidith’ ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (eidith)

The downloaded source packages are in
	‘/private/var/folders/pj/1g76ddnj46l9mtcs9f8m5lxm0000gp/T/RtmpwfPi5y/downloaded_packages’
```

**Comment by noamross** [comment]
OK, thanks.  Just fixed the typo, the warning should go away when we build Windows and Mac binaries, but that will be for 0.3.0.  We should do that very soon! Mostly I want to make sure that the mock data stuff that @calebasaraba and @PanditPranav are working on is set.
