### ISSUE TITLE
Move away from drat-based installs

### ISSUE THREAD

**Issue by noamross** [ecohealthalliance/eidith#58]
**drat** based installs are a bit onerous on us, leading to lag in releases, and are currently held up due to a bug in that package.  They're really not necessary for this package without compiled code, so let's get rid of them:

-  [x] Remove the tarballs from the project website
-  [x] Remove package-building from the build process / Makefile
-  [x] Change documentation for the default non-dev install to be `source("https://install-github.me/ecohealthalliance/eidith")`
- [x] Test this install on someone's Windows / non-Xtools computer
- [x] Merge to master

**Comment by calebasaraba** [comment]
Master now up to date, using install-github.me checked on windows and mac machines without tools

**Comment by noamross** [comment]
Great, thanks!
