### ISSUE TITLE
Package load errors on Windows

### ISSUE THREAD

**Issue by noamross** [ecohealthalliance/eidith#76]
@DeniseJGreig encountered an error loading the package that appears to have to do with the initial database connection and may be due to package versioning.

The following is the console log following `eidith::ed_db_download()` without loading the packages.  The tables download successfully but the the error occurs in final wrap-up:

```
Importing...
All database tables have successfully downloaded!
Error: Columns unique_idt_name not found
In addition: Warning messages:
1: package ‘bindrcpp’ was built under R version 3.4.4 
2: In connection_release(conn@ptr) :
  There are 1 result in use. The connection will be released when they are closed

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     compiler_3.4.0   pillar_1.2.2     dbplyr_1.2.1     bindr_0.1.1      tools_3.4.0      digest_0.6.15    bit_1.1-12      
 [9] jsonlite_1.5     lubridate_1.7.4  RSQLite_2.1.0    memoise_1.1.0    tibble_1.4.2     pkgconfig_2.0.1  rlang_0.2.0      DBI_0.8         
[17] cli_1.0.0        rstudioapi_0.7   curl_3.2         yaml_2.1.18      dplyr_0.7.4      httr_1.3.1       stringr_1.3.0    janitor_1.0.0   
[25] htmlwidgets_1.2  rappdirs_0.3.1   hms_0.4.2        bit64_0.9-7      DT_0.4           glue_1.2.0       R6_2.2.2         tidyr_0.8.0     
[33] purrr_0.2.4      readr_1.1.1      blob_1.1.1       magrittr_1.5     htmltools_0.3.6  assertthat_0.2.0 eidith_0.4       stringi_1.1.7   
[41] crayon_1.3.4   
 
> library(eidith)
There are unspecified errors in the local EIDITH database. If problems persist after using ed_db_download(), see ?ed_contact.

Error in grouped_df_impl(data, unname(vars), drop): Column `t_name` is unknown

Error: package or namespace load failed for ‘eidith’:
 .onAttach failed in attachNamespace() for 'eidith', details:
  call: grouped_df_impl(data, unname(vars), drop)
  error: Column `t_name` is unknown
```

**Comment by DeniseJGreig** [comment]
I updated my version of R to 3.5 and now have some additional information. When I ran
source("https://install-github.me/ecohealthalliance/eidith")
I got a bunch of Rd warnings:

Downloading GitHub repo ecohealthalliance/eidith@master
Installing 67 packages: assertthat, BH, bindr, bindrcpp, bit, bit64, blob, cli, colorspace, crayon, crosstalk, curl, DBI, dbplyr, dichromat, digest, dplyr, DT, getPass, ggplot2, glue, gtable, hms, htmltools, htmlwidgets, httpuv, httr, janitor, jsonlite, labeling, later, lazyeval, lubridate, magrittr, memoise, mime, munsell, openssl, pillar, pkgconfig, plogr, plyr, prettyunits, promises, purrr, R6, rappdirs, RColorBrewer, Rcpp, readr, reshape2, rlang, RSQLite, rstudioapi, scales, shiny, snakecase, sourcetools, stringi, stringr, tibble, tidyr, tidyselect, utf8, viridisLite, xtable, yaml
package ‘assertthat’ successfully unpacked and MD5 sums checked
package ‘BH’ successfully unpacked and MD5 sums checked
package ‘bindr’ successfully unpacked and MD5 sums checked
package ‘bindrcpp’ successfully unpacked and MD5 sums checked
package ‘bit’ successfully unpacked and MD5 sums checked
package ‘bit64’ successfully unpacked and MD5 sums checked
package ‘blob’ successfully unpacked and MD5 sums checked
package ‘cli’ successfully unpacked and MD5 sums checked
package ‘colorspace’ successfully unpacked and MD5 sums checked
package ‘crayon’ successfully unpacked and MD5 sums checked
package ‘crosstalk’ successfully unpacked and MD5 sums checked
package ‘curl’ successfully unpacked and MD5 sums checked
package ‘DBI’ successfully unpacked and MD5 sums checked
package ‘dbplyr’ successfully unpacked and MD5 sums checked
package ‘dichromat’ successfully unpacked and MD5 sums checked
package ‘digest’ successfully unpacked and MD5 sums checked
package ‘dplyr’ successfully unpacked and MD5 sums checked
package ‘DT’ successfully unpacked and MD5 sums checked
package ‘getPass’ successfully unpacked and MD5 sums checked
package ‘ggplot2’ successfully unpacked and MD5 sums checked
package ‘glue’ successfully unpacked and MD5 sums checked
package ‘gtable’ successfully unpacked and MD5 sums checked
package ‘hms’ successfully unpacked and MD5 sums checked
package ‘htmltools’ successfully unpacked and MD5 sums checked
package ‘htmlwidgets’ successfully unpacked and MD5 sums checked
package ‘httpuv’ successfully unpacked and MD5 sums checked
package ‘httr’ successfully unpacked and MD5 sums checked
package ‘janitor’ successfully unpacked and MD5 sums checked
package ‘jsonlite’ successfully unpacked and MD5 sums checked
package ‘labeling’ successfully unpacked and MD5 sums checked
package ‘later’ successfully unpacked and MD5 sums checked
package ‘lazyeval’ successfully unpacked and MD5 sums checked
package ‘lubridate’ successfully unpacked and MD5 sums checked
package ‘magrittr’ successfully unpacked and MD5 sums checked
package ‘memoise’ successfully unpacked and MD5 sums checked
package ‘mime’ successfully unpacked and MD5 sums checked
package ‘munsell’ successfully unpacked and MD5 sums checked
package ‘openssl’ successfully unpacked and MD5 sums checked
package ‘pillar’ successfully unpacked and MD5 sums checked
package ‘pkgconfig’ successfully unpacked and MD5 sums checked
package ‘plogr’ successfully unpacked and MD5 sums checked
package ‘plyr’ successfully unpacked and MD5 sums checked
package ‘prettyunits’ successfully unpacked and MD5 sums checked
package ‘promises’ successfully unpacked and MD5 sums checked
package ‘purrr’ successfully unpacked and MD5 sums checked
package ‘R6’ successfully unpacked and MD5 sums checked
package ‘rappdirs’ successfully unpacked and MD5 sums checked
package ‘RColorBrewer’ successfully unpacked and MD5 sums checked
package ‘Rcpp’ successfully unpacked and MD5 sums checked
package ‘readr’ successfully unpacked and MD5 sums checked
package ‘reshape2’ successfully unpacked and MD5 sums checked
package ‘rlang’ successfully unpacked and MD5 sums checked
package ‘RSQLite’ successfully unpacked and MD5 sums checked
package ‘rstudioapi’ successfully unpacked and MD5 sums checked
package ‘scales’ successfully unpacked and MD5 sums checked
package ‘shiny’ successfully unpacked and MD5 sums checked
package ‘snakecase’ successfully unpacked and MD5 sums checked
package ‘sourcetools’ successfully unpacked and MD5 sums checked
package ‘stringi’ successfully unpacked and MD5 sums checked
package ‘stringr’ successfully unpacked and MD5 sums checked
package ‘tibble’ successfully unpacked and MD5 sums checked
package ‘tidyr’ successfully unpacked and MD5 sums checked
package ‘tidyselect’ successfully unpacked and MD5 sums checked
package ‘utf8’ successfully unpacked and MD5 sums checked
package ‘viridisLite’ successfully unpacked and MD5 sums checked
package ‘xtable’ successfully unpacked and MD5 sums checked
package ‘yaml’ successfully unpacked and MD5 sums checked
Installing package into ‘C:/Users/dgreig/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'eidith' ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'eidith'
    finding HTML links ... done
    ed2_expand_long                         html  
    ed2_expand_wide                         html  
    ed2_metadata                            html  
    ed2_table                               html  
    ed_auth                                 html  
    ed_contact                              html  
    ed_db_check_status                      html  
    finding level-2 HTML links ... done

Rd warning: C:/Users/dgreig/AppData/Local/Temp/RtmpmedUGk/remotes11a03966172/ecohealthalliance-eidith-5c31777/man/ed_db_check_status.Rd:23: missing link 'ed_db_updates'
    ed_db_delete                            html  
    ed_db_detailed_status                   html  
    ed_db_download                          html  
Rd warning: C:/Users/dgreig/AppData/Local/Temp/RtmpmedUGk/remotes11a03966172/ecohealthalliance-eidith-5c31777/man/ed_db_download.Rd:42: missing link 'ed_db_status'
Rd warning: C:/Users/dgreig/AppData/Local/Temp/RtmpmedUGk/remotes11a03966172/ecohealthalliance-eidith-5c31777/man/ed_db_download.Rd:42: missing link 'ed_db_updates'
    ed_db_export                            html  
Rd warning: C:/Users/dgreig/AppData/Local/Temp/RtmpmedUGk/remotes11a03966172/ecohealthalliance-eidith-5c31777/man/ed_db_export.Rd:28: missing link 'ed_db_status'
Rd warning: C:/Users/dgreig/AppData/Local/Temp/RtmpmedUGk/remotes11a03966172/ecohealthalliance-eidith-5c31777/man/ed_db_export.Rd:28: missing link 'ed_db_updates'
    ed_fasta                                html  
    ed_get                                  html  
    ed_metadata                             html  
    ed_mock                                 html  
    ed_process                              html  
    ed_table                                html  
Rd warning: C:/Users/dgreig/AppData/Local/Temp/RtmpmedUGk/remotes11a03966172/ecohealthalliance-eidith-5c31777/man/ed_table.Rd:46: missing link 'mock data'
    ed_tables_conn                          html  
    eidith                                  html  
    endpoints                               html  
** building package indices
** installing vignettes
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (eidith)
In R CMD INSTALL

**Comment by DeniseJGreig** [comment]
Then....similar errors as before:
library(eidith)
There are unspecified errors in the local EIDITH database. If problems persist after using ed_db_download(), see ?ed_contact.

Error in grouped_df_impl(data, unname(vars), drop): Column `t_name` is unknown

Error: package or namespace load failed for ‘eidith’:
 .onAttach failed in attachNamespace() for 'eidith', details:
  call: grouped_df_impl(data, unname(vars), drop)
  error: Column `t_name` is unknown

**Comment by calebasaraba** [comment]
@DeniseJGreig installation issues have been addressed
