### ISSUE TITLE
Object not found:  auto_processed_name

### ISSUE THREAD

**Issue by davidjmciver** [ecohealthalliance/eidith#93]
Hi EHA team,

When I'm trying to use the ed2_expand_wide function, it seems I'm only able to do this with some, but not all variables (all of which are multi-response). 

For example, I can successfully expand "drinking_water_sources" and "travel_reason", but I can not expand "animal_human_interfaces" or "insect_vectors". As far as I can tell, I'm using the proper variable names as created under the auto_processed_name column in the ?ed2_metadata table. 

The specific error I get is: 
Error in mutate_impl(.data, dots) : 
  Evaluation error: object 'disease_transmission_interfaces' not found.

I'm not sure what I am doing wrong here - though admit I'm an R amateur. Any help you could offer would be appreciated. 

Thanks a lot! 

Dave McIver - Metabiota

**Comment by noamross** [comment]
Can you paste in the code that you are running that generates the error?

**Comment by davidjmciver** [comment]
Sure...

> humans <- ed2_human()
> humans_wide <- ed2_expand_wide(humans, travel_reason)
> humans_wide <- ed2_expand_wide(humans, disease_transmission_interfaces)
Error in mutate_impl(.data, dots) : 
  Evaluation error: object 'disease_transmission_interfaces' not found.
>

**Comment by noamross** [comment]
One of the other things we do in the package is reduce redundancy between tables. 
`disease_transmission_interfaces` is an event-level piece of data, so it is not in the `ed2_humans()` table, only the `ed2_events()` table.  You'll see in the metadata table that it has `DROP` designation under the human table.

We've written a guide to the relationships between tables and how to link them here: https://ecohealthalliance.github.io/eidith/articles/p2_data_structure.html

**Comment by davidjmciver** [comment]
Great, thanks a lot Noam!
D
